# Generated by Django 3.1 on 2020-09-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_story_evaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='evaluated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
